# Generated by Django 4.2.14 on 2026-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_chapter_id_alter_favorite_id_alter_novel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否VIP会员'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP到期时间'),
        ),
    ]
