# Generated by Django 4.2.14 on 2026-05-29 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_user_is_vip_user_vip_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='publish_status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '已下架')], default=1, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='novel',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '审核中'), (2, '已发布'), (3, '驳回')], default=2, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='novel',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='作者账号'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='标签(逗号分隔)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='作者简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='是否作者'),
        ),
        migrations.AddField(
            model_name='user',
            name='pen_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='笔名'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.IntegerField(choices=[(0, '连载中'), (1, '已完结'), (2, '已下架')], default=0, verbose_name='连载状态'),
        ),
    ]
