# Generated by Django 4.2.14 on 2026-05-29 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_chapter_publish_status_chapter_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='封面'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('rating', models.IntegerField(default=0, verbose_name='评分(0-5,0表示纯评论)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novels.novel', verbose_name='小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
