# Generated by Django 4.2.14 on 2026-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novel_cover_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='position',
            field=models.IntegerField(default=0, verbose_name='阅读位置(%)'),
        ),
    ]
