# Generated by Django 4.2.14 on 2026-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_add_bookmark_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='广告标题')),
                ('ad_type', models.CharField(choices=[('banner', '横幅广告'), ('popup', '弹窗广告'), ('sidebar', '侧边栏广告')], max_length=20, verbose_name='广告类型')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片地址')),
                ('link_url', models.URLField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('position', models.CharField(choices=[('home_top', '首页顶部'), ('home_sidebar', '首页侧边栏'), ('reader_bottom', '阅读页底部'), ('reader_popup', '阅读页弹窗')], max_length=50, verbose_name='展示位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='曝光次数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'advertisement',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('announcement_type', models.CharField(choices=[('notice', '通知'), ('maintenance', '维护公告'), ('activity', '活动公告')], default='notice', max_length=20, verbose_name='公告类型')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
