# Generated by Django 4.2.14 on 2026-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_user_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_adapted',
            field=models.BooleanField(default=False, verbose_name='影视改编'),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='总编推荐'),
        ),
        migrations.AddField(
            model_name='novel',
            name='recommend_comment',
            field=models.TextField(blank=True, default='', verbose_name='总编评语'),
        ),
        migrations.AddField(
            model_name='novel',
            name='topic_tag',
            field=models.CharField(blank=True, default='', help_text='女频专题/男频专题/空表示不参与专题', max_length=20, verbose_name='专题标签'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '审核中'), (2, '已发布'), (3, '驳回')], default=1, verbose_name='审核状态'),
        ),
    ]
