# Generated by Django 4.2.14 on 2026-06-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_novel_is_adapted_novel_is_recommended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('plan_type', models.CharField(choices=[('monthly', '月卡'), ('quarterly', '季卡'), ('yearly', '年卡')], max_length=20, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格(元)')),
                ('days', models.IntegerField(verbose_name='会员天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '充值套餐',
                'verbose_name_plural': '充值套餐',
                'db_table': 'recharge_plan',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SigninReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(unique=True, verbose_name='连续签到天数')),
                ('coins', models.IntegerField(default=10, verbose_name='奖励币数')),
                ('extra_coins', models.IntegerField(default=0, verbose_name='额外奖励(连续签到)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '签到奖励配置',
                'verbose_name_plural': '签到奖励配置',
                'db_table': 'signin_reward',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='novels.rechargeplan', verbose_name='套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'db_table': 'recharge_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigninRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_date', models.DateField(verbose_name='签到日期')),
                ('coins_earned', models.IntegerField(default=10, verbose_name='获得币数')),
                ('consecutive_days', models.IntegerField(default=1, verbose_name='连续天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signin_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'signin_record',
                'ordering': ['-signin_date'],
                'unique_together': {('user', 'signin_date')},
            },
        ),
    ]
