# Generated by Django 4.2.14 on 2026-06-06 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_add_signin_recharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='签到日期')),
                ('reward_coins', models.IntegerField(default=0, verbose_name='获得虚拟币')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
            ],
            options={
                'db_table': 'checkin',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckInConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reward', models.IntegerField(default=10, verbose_name='每日签到奖励币数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checkin_config',
            },
        ),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('plan_type', models.CharField(choices=[('monthly', '月卡'), ('quarterly', '季卡'), ('yearly', '年卡')], max_length=20, verbose_name='套餐类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额(元)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'membership_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='rechargeorder',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='rechargeorder',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='signinrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='signinrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='SigninReward',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='is_adapted',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='is_recommended',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='recommend_comment',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='topic_tag',
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='虚拟币余额'),
        ),
        migrations.DeleteModel(
            name='RechargeOrder',
        ),
        migrations.DeleteModel(
            name='RechargePlan',
        ),
        migrations.DeleteModel(
            name='SigninRecord',
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'check_date')},
        ),
    ]
