# Generated by Django 4.2.14 on 2026-06-07 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_add_checkin_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='作者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_follow',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'author_name')},
            },
        ),
    ]
